
{{- range $key, $value := .Values.Operators }}
{{- $operatorname := printf "%s" .name -}}
{{- $projectname := printf "%s" .project -}}
{{- $operatorsource := printf "%s" .source -}}
{{- $operatorsourcenamepsace := printf "%s" .source_namespace -}}
{{- $operatorapigroup := printf "%s" .api_group -}}
{{- $operatorplanapproval := printf "%s" .plan_approval -}}
{{- $operatorchannel := printf "%s" .channel -}}
---
{{ if ne $projectname "openshift-operators" }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ $projectname }}
  namespace: {{ $projectname }}
spec:
  targetNamespaces:
  - {{ $projectname }}
{{ end }}
{{ end }}