{{ if eq .Values.rolecreate "true" }}
{{- range $key, $value := .Values.PROJECTS }}
{{- $projectname := printf "%s" .NAME -}}
{{- $displayname := printf "%s" .DISPLAYNAME -}}
{{- $description := printf "%s" .DESCRIPTION -}}
{{- $adminuser := printf "%s" .ADMIN_USER -}}
{{- $requester := printf "%s" .REQUESTING_USER -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ $projectname }}-admin-binding
  namespace: {{ $projectname }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $projectname }}-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ $adminuser }}
{{ end }}
{{ end }}