{{- range $key, $value := .Values.PROJECTS }}
{{- $projectname := printf "%s" .NAME -}}
{{- $displayname := printf "%s" .DISPLAYNAME -}}
{{- $description := printf "%s" .DESCRIPTION -}}
{{- $adminuser := printf "%s" .ADMIN_USER -}}
{{- $requester := printf "%s" .REQUESTING_USER -}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ $projectname }}-admin
  namespace: {{ $projectname }}
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
{{ end }}